service: music-streaming-api

provider:
  name: aws
  runtime: python3.12
  region: eu-north-1
  memorySize: 256
  timeout: 29
  environment:
    BUCKET_NAME: my-music-app-files
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::my-music-app-files/*

functions:
  uploadMusicFile:
    handler: handler.lambda_handler
    events:
      - http:
          path: song
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false
            methods:
              - OPTIONS
              - POST

custom:
  apiGateway:
    binary:
      types:
        - '*/*'

plugins:
  - serverless-apigw-binary
